# Introducing NumPy


Python is convenient, but it can also be slow. However, it does allow us to access libraries that execute faster code written in languages like C. NumPy is one such library: it provides **fast alternatives to math operations in Python** and is designed to work efficiently with groups of numbers - like matrices.
NumPy is a large library and we are only going to scratch the surface of it here.

This hands on tutorial includes the following: <br>
- #### Data Types and Shapes
    -  Scalar <br>
    -  Vectors <br>
    -  Matrices <br>
    - Tensors <br>
    - Changing shapes* <br>
    - Commonly used initializations <br>
- #### Element wise operation
    -  The Python way <br>
    -  The NumPy way <br>
    -  Element-wise Matrix Operations <br>
- #### NumPy Matrix Multiplication
    -  Element-wise Multiplication <br>
    -  Matrix Product <br>
    -  NumPys ```dot``` function <br>
    -  Transpose <br>
    -  A real use case <br>
- #### Sorting, Subsetting, Slicing, Splitting and Indexing

### Importing NumPy

When importing the NumPy library, the convention we'll see used most often – including here – is to name it ```np```, like so:

In [226]:
import numpy as np

In [227]:
x = np.array(5)
print(x)

5


Now we can use the library by prefixing the names of functions and types with ```np.```, which we'll see in the following examples.

### Data Types and Shapes

The most common way to work with numbers in NumPy is through ```ndarray``` objects. They are similar to Python lists, but can have any number of dimensions. Also, ```ndarray``` supports fast math operations, which is just what we want. <br>
Since it can store any number of dimensions, we can use ```ndarray```'s to represent any of the data types: **scalars**, **vectors**, **matrices**, or **tensors**.

### Scalars

Scalars in NumPy are a bit more involved than in Python. Instead of Python’s basic types like ```int```, ```float```, etc., NumPy lets we specify signed and unsigned types, as well as different sizes. So instead of Python’s ```int```, we have access to types like ```uint8```, ```int8```, ```uint16```, ```int16```, and so on. <br>
These types are important because every object we make (vectors, matrices, tensors) eventually stores scalars. And when we create a NumPy array, we can specify the type - but **every item in the array must have the same type**. In this regard, NumPy arrays are more like C arrays than Python **lists**.

If we want to create a NumPy array that holds a scalar, we can do so by passing the value to NumPy's array function, like so:

In [228]:
s = np.array(5)
print (s)

5


In [229]:
print(type(s))

<class 'numpy.ndarray'>


In [230]:
s.dtype

dtype('int64')

We can see the shape of our arrays by checking their ```shape``` attribute. So if we executed this code:

In [231]:
print(s.shape)

()


Here, this empty pair of parenthesis, ```()``` indicates that it has zero dimensions.

Even though scalars are inside arrays, we still use them like a normal scalar. So we could type:

In [232]:
x = 3  + s 
print(x)

8


In [233]:
print(type(x))

<class 'numpy.int64'>


In [234]:
x.dtype

dtype('int64')

If we were to check the type of x, we'd find it is probably ```numpy.int64```, because its working with NumPy types, not Python types.

Even scalar types support most of the array functions. so we can call ```x.shape``` and it would return ```()``` because it has zero dimensions, even though it is not an array. If we tried that with a normal Python scalar, we'd get an error.

In [11]:
print(x.shape)

x = 8

print(x.shape)

()


AttributeError: 'int' object has no attribute 'shape'

### Vectors

To create a vector, we'd pass a Python list to the array function, like this:

In [235]:
v = np.array([1,2,3])
print (v)

[1 2 3]


If we check a vector's shape attribute, it will return a single number representing the vector's one-dimensional length.

In [236]:
print(v.shape)

(3,)


Now that there is a number, we can see that the shape is a tuple with the sizes of each of the ```ndarray```'s dimensions. For scalars it was just an empty tuple, but vectors have one dimension, so the tuple includes a number and a comma. <br>
Python doesn’t understand ```(3)``` as a tuple with one item, so it requires the comma.

We can access an element within the vector using indices, like this:

In [237]:
x = v[1]
print(x)

2


NumPy also supports advanced indexing techniques. For example, to access the items from the second element onward, we would say:

In [238]:
print(v[1:])
print('\n')
print(v[:2])

[2 3]


[1 2]


### Matrices

We can create matrices using NumPy's array function, similar to that of vectors. However, instead of just passing in a list, we need to supply a list of lists, where each list represents a row. So to create a 3x3 matrix containing the numbers one through nine, we could do this:


In [241]:
[[1,2,3],
[4,5,6],
[7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [242]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m
print("m = \n",m, '\n' )
print("m.shape: ",m.shape)

m = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

m.shape:  (3, 3)


```m``` is thus a ```(3, 3)``` tuple. This indicates that it has two dimensions, each of size 3.
We can access elements of matrices just like vectors, but using additional index values. So to find the number 6 in the above matrix, we'd access

In [29]:
print(m[1][2])

6


Doing the same with a list will give an error:

In [30]:
m = [[1,2,3], [4,5,6], [7,8,9]]
print("m = \n",m)
print("m.shape: ",m.shape)

m = 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


AttributeError: 'list' object has no attribute 'shape'

But, each element can be selected via the same method:

In [25]:
print(m[1][2])

6


### Tensors

Tensors are just like vectors and matrices, **but they can have more dimensions**. For example, to create a 3x3x2x1 tensor, we could do the following:

In [26]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],\
              [[[7],[8]],[[9],[10]],[[11],[12]]], \
              [[[13],[14]],[[15],[16]],[[17],[18]]]])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [18]]]])

In [35]:
np.array([ [[[1,1],[1,1]], [[1,1],[1,1]]], [[[1,1],[1,1]], [[1,1],[1,1]]]
    
]).shape

(2, 2, 2, 2)

In [44]:
t[1][2][1][0]

12

And ```t.shape``` would return 

In [36]:
print(t.shape)

(3, 3, 2, 1)


We can access items just like with matrices, but with more indices. So ```t[2][1][1][0]``` will return

In [37]:
print(t[2][1][1][0])

16


There is also a function called ```size``` which returns the total number of elements in an array. So for ```t```

In [38]:
print(t.size)

18


And we can clearly see from the figure above that the total number of elements in ```t``` are, as a matter of fact, 18.

In [ ]:
# Task:
# Make an array of all 1's which returns the shape as follows:
# shape = (4,4,3,3,2,1)

### Changing Shapes <br>
Sometimes we'll need to change the shape of our data without actually changing its contents. For example, we may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional. There are two ways we can do that.

Let's say we have the following vector:

In [291]:
v = np.array([1,
              2,
              3,
              4])

Calling v.shape would return 

In [292]:
print(v.shape)

(4,)


In [293]:
print(v)

[1 2 3 4]


In [294]:
new  = v.reshape(2,2)
print(new)

[[1 2]
 [3 4]]


But what if we want a 1x4 matrix? We can accomplish that with the reshape function, like so:

In [295]:
x = v.reshape(1,4)

In [296]:
x

array([[1, 2, 3, 4]])

In [297]:
y=v.reshape(-1,1)
y.shape

(4, 1)

Calling x.shape would return 

In [298]:
print(x.shape)

(1, 4)


In [299]:
print(x)

[[1 2 3 4]]


Now, If we wanted a 4x1 matrix, we could do this:

In [300]:
x = v.reshape(4,1)
print(x.shape)
print(x)

(4, 1)
[[1]
 [2]
 [3]
 [4]]


For a 2x2 matrix:

In [301]:
x = v.reshape(2,2)
print(x.shape)
print(x)

(2, 2)
[[1 2]
 [3 4]]


One more thing about reshaping NumPy arrays: if we see code from experienced NumPy users, we will often see them use a special slicing syntax instead of calling reshape. Using this syntax, the previous two examples would look like this:

In [303]:
v, v.shape

(array([1, 2, 3, 4]), (4,))

In [304]:
v[None,:], v[None,:].shape

(array([[1, 2, 3, 4]]), (1, 4))

In [306]:
v[:, None], v[:, None].shape

(array([[1],
        [2],
        [3],
        [4]]),
 (4, 1))

In [267]:
x = v[None, :]
print(x.shape)

(1, 4)


In [312]:
v.reshape(-1,4).shape

(1, 4)

In [313]:
x.shape, x

((2, 2),
 array([[1, 2],
        [3, 4]]))

     or

In [276]:
x.T, x.T.shape

(array([[1, 2, 3, 4]]), (1, 4))

In [273]:
x[None,:].shape

(1, 4, 1)

In [269]:
x = v[:, None]
print(x.shape)

(4, 1)


In [254]:
np.arange(8,15)

array([ 8,  9, 10, 11, 12, 13, 14])

In [80]:
x

array([[1],
       [2],
       [3],
       [4]])

In [57]:
x=v[1:,None]
print(x,x.shape)

[[2]
 [3]
 [4]] (3, 1)


In [286]:
c=np.array([[1,2,3,4], [5,6,7,8]])
c.shape

(2, 4)

In [281]:
c.T.shape

(4, 2)

In [287]:
c[None:,].shape

(2, 4)

In [290]:
c[:,None], c[:,None].shape

(array([[[1, 2, 3, 4]],
 
        [[5, 6, 7, 8]]]),
 (2, 1, 4))

These lines create a slice that looks at all of the items of v but asks NumPy to add a new dimension of size 1 for the associated axis. It may look strange to us now, but it's a common technique so it's good to be aware of it.

Now, let's suppose we have a matrix ```A```

In [314]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


and we need to reshape it to a 2x6 matrix. We could do this:

In [315]:
x = A.reshape(2,6)
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


And if we want to take the tensor ```t``` and reshape it to a 6x3 matrix, we can also do that

In [316]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[18]]]])
print("t.shape is ",t.shape,"\n")

x = t.reshape(6,3)
print("x = \n",x)
print("x.shape is ",x.shape,"\n")

t.shape is  (3, 3, 2, 1) 

x = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
x.shape is  (6, 3) 



The thing to note here is that ```ndarray```'s can be shaped to any shape as long as the total number of tensor elements remain the same. For example

In [317]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m, "\n")
print('Shape of m:' ,m.shape, '\n Size of m: ', m.size)
x = m.reshape(2,4)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Shape of m: (3, 3) 
 Size of m:  9


ValueError: cannot reshape array of size 9 into shape (2,4)

Here, the matrix ```m``` has a size ```(3,3)``` where as ```m.reshape(2,4)``` is asking it to be rearranged to a dimension ```(2,4)``` which is not possible to do.

### Commonly used initializations

Many a times typing a ```np.array``` becomes a tedious task. To facilitate in this difficulty, NumPy provides ways to initialize bigger arrays with simple functions.

In [63]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Thus ```np.zeros((3,4))``` initializes a NumPy array having dimensions 3x4 and all element values equal to ```0```'s

Similarly the ```np.ones()``` function will create a matrix of the desired dimensions with all element values equal to ```1```

In [64]:
np.ones((4,4,3,3,2,1))

array([[[[[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]]],



        [[[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]]],



        [[[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]]],



    

In [65]:
a = np.ones((3,2,2))
print(a)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


NumPy also provides us with the option of randomly initializing the element values in it's arrays. The ```np.random.rand()``` function creates an array of the given shape and populates it with random samples from a uniform distribution over ```[0, 1)```.

In [66]:
a = np.random.rand(3,5)
print(a)

[[0.56838298 0.31697436 0.18053288 0.55843754 0.98263946]
 [0.83144027 0.69973587 0.68898312 0.41292445 0.98046464]
 [0.89308703 0.60088155 0.81136558 0.84297428 0.35456488]]


In [67]:
b=np.array([3,4])
b.mean()

3.5

And, the ```np.random.randn()``` does the same but with samples taken from a normal distribution given by $  \frac{1}{{\sigma \sqrt {2\pi } }}e^{{(x-\mu)}^2 / 2\sigma^2 } $ having mean ($\mu$) 0 and variance ($\sigma^2$) 1.

In [75]:
a = np.random.randn(2000,2000)
print(a.mean()) # For a large enough array, this value converges to 0
print(np.std(a**2)) # For a large enough array this value converges to 1
print(a)

-0.00020621186196341238
1.4114368898580212
[[-4.14054859e-01 -1.23689611e-01 -1.21237568e-03 ...  1.21121016e+00
   7.00122574e-01 -6.75866787e-01]
 [-4.32761210e-01 -2.72754343e-01  1.10270068e+00 ...  1.46376123e+00
   1.64235269e-01  2.43269454e-01]
 [-4.25487557e-01  2.19969051e-01 -7.35224206e-01 ...  1.15481110e-01
   5.92259813e-02  1.44396296e+00]
 ...
 [-6.78923623e-01 -1.38498172e+00 -1.03632336e+00 ... -1.38486705e+00
  -1.06784208e+00  1.27987519e+00]
 [-1.61184994e-02 -4.31099204e-01 -3.82319226e-01 ...  4.37871792e-01
   3.70026551e-01  1.17144934e+00]
 [-1.18903238e-01 -1.46241982e+00 -1.11850012e+00 ... -1.74723003e+00
   8.36970565e-01 -2.00239455e+00]]


In [76]:
a.min(), a.max(), a.shape,

AttributeError: 'numpy.ndarray' object has no attribute 'count'

## Element-wise operations

### The Python way

Suppose we had a list of numbers, and we wanted to add 5 to every item in the list. Without NumPy, we might do something like this:

In [123]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
print(values)

[6, 7, 8, 9, 10]


That makes sense, but it's a lot of code to write and it runs slowly because it's pure Python. <br> <br>
**Note:** Just in case we aren't used to using operators like +=, that just means "*add these two items and then store the result in the left item.*" It is a more succinct way of writing ```values[i] = values[i] + 5```.

### The NumPy way

In NumPy, we could do the following:

In [83]:
values = [1,2,3,4,5]
values = np.array(values) +5
print(values)

[ 6  7  8  9 10]


Creating that array may seem odd, but normally we'll be storing our data in ndarrays anyway. So if we already had an ```ndarray``` named variable, we would have just done:

In [126]:
values = values-5     #back to the original values
print(values)
values += 5
print(values)

[1 2 3 4 5]
[ 6  7  8  9 10]


We should point out, NumPy actually has functions for things like adding, multiplying, etc. But it also supports using the standard math operators. So the following two lines are equivalent:

In [84]:
x = np.multiply(values, 5)
print(x)
x = values * 5
print(x)

[30 35 40 45 50]
[30 35 40 45 50]


We will usually use the operators instead of the functions because they are more convenient to type and easier to read, but it's really just personal preference.

One more example of operating with scalars and ndarrays. Let's say we have a matrix m and we want to reuse it, but first we need to set all its values to zero. Easy, just multiply by zero and assign the result back to the matrix, like this:

In [319]:
import numpy as np
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

m *= 0
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Element-wise Matrix Operations
The same functions and operators that work with scalars and matrices also work with other dimensions. We just need to make sure that the items we perform the operation on have compatible shapes.
Let's say we want to get the squared values of a matrix. That's simply ```x = m * m``` (or if we want to assign the value back to m, it's just ```m *= m``` <br>
This works because it's an element-wise multiplication between two identically-shaped matrices. (In this case, they are shaped the same because they are actually the same object.) <br> <br>
Let's look at the following example:

In [320]:
a = np.array([[1,3],[5,7]])
a_list = [[1,3],[5,7]]
print("a = \n",a,"\n")
print("a_list = \n",a_list,"\n")

b = np.array([[2,4],[6,8]])
b_list = [[2,4],[6,8]]
print("b = \n",b,"\n")
print("b_list = \n",b_list,"\n")

print("a + b = \n",a + b,"\n")
print("a_list + b_list = \n",a_list + b_list,"\n")

a = 
 [[1 3]
 [5 7]] 

a_list = 
 [[1, 3], [5, 7]] 

b = 
 [[2 4]
 [6 8]] 

b_list = 
 [[2, 4], [6, 8]] 

a + b = 
 [[ 3  7]
 [11 15]] 

a_list + b_list = 
 [[1, 3], [5, 7], [2, 4], [6, 8]] 



We can see that simple lists yield quite a different result. <br>
And, if we try working with incompatible shapes we'd get an error:

In [321]:
a = np.array([[1,3],[5,7]])
print("a = \n",a,"\n") 

c = np.array([[2,3,6],[4,5,9],[1,8,7]])
print("c = \n",c,"\n")

print("a.shape: ",a.shape)
print("c.shape: ",c.shape,"\n")

print("a + c = \n",a + c)

a = 
 [[1 3]
 [5 7]] 

c = 
 [[2 3 6]
 [4 5 9]
 [1 8 7]] 

a.shape:  (2, 2)
c.shape:  (3, 3) 



ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

## NumPy Matrix Multiplication
Now we'll talk about how to do matrix multiplication with NumPy. It's important to know that NumPy supports several types of matrix multiplication.

### Element-wise Multiplication
We have seen some element-wise multiplication already. we can also accomplish that with the ```multiply``` function or the ```*``` operator. Just to revisit, it would look like this:


In [322]:
m = np.array([[1,2,3],[4,5,6]])
print("m = \n",m,"\n")

n = m * 0.25
print("n = \n",n,"\n")

print("m * n = \n",m * n,"\n")

print("np.multiply(m, n)= \n",np.multiply(m, n))

m = 
 [[1 2 3]
 [4 5 6]] 

n = 
 [[0.25 0.5  0.75]
 [1.   1.25 1.5 ]] 

m * n = 
 [[0.25 1.   2.25]
 [4.   6.25 9.  ]] 

np.multiply(m, n)= 
 [[0.25 1.   2.25]
 [4.   6.25 9.  ]]


### Matrix Product
To find the matrix product, we use NumPy's ```matmul``` function. This operation is exclusive for NumPy arrays <br>
If we have compatible shapes, then it's as simple as this:

In [333]:
print(a)
print('\t')
print(b)

[[1 3]
 [5 7]]
	
[[2 4]
 [6 8]]


In [334]:
np.dot(a,b)

array([[20, 28],
       [52, 76]])

In [335]:
np.matmul(a,b)

array([[20, 28],
       [52, 76]])

In [95]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print("a = \n",a)
print("a.shape: ",a.shape, "\n")

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("b = \n",b)
print("b.shape: ", b.shape, "\n")

c = np.matmul(a, b) # (2,4)*(4,3)
print("c = \n",c)
print("c.shape: ",c.shape,"\n")

a = 
 [[1 2 3 4]
 [5 6 7 8]]
a.shape:  (2, 4) 

b = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b.shape:  (4, 3) 

c = 
 [[ 70  80  90]
 [158 184 210]]
c.shape:  (2, 3) 



In [96]:
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [122]:
(np.ones((4,2,1))*np.ones((1,2,3))).shape



(4, 2, 3)

If our matrices have incompatible shapes, we'll get an error, like the following:

In [84]:
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

This is because for matrices $a.b \neq b.a  $ 

### NumPy's ```dot``` function
We may sometimes see NumPy's ```dot``` function in places where we would expect a ```matmul```. It turns out that the results of ```dot``` and ```matmul``` are the same if the matrices are two dimensional. <br>
So these two results are equivalent:

In [336]:
a = np.array([[1,2],[3,4]])
print("a = \n",a,"\n")

print("np.dot(a,a) = \n",np.dot(a,a),"\n")

print("a.dot(a) = \n",a.dot(a),"\n")  # you can call `dot` directly on the `ndarray`

print("np.matmul(a,a) = \n",np.matmul(a,a),"\n")

a = 
 [[1 2]
 [3 4]] 

np.dot(a,a) = 
 [[ 7 10]
 [15 22]] 

a.dot(a) = 
 [[ 7 10]
 [15 22]] 

np.matmul(a,a) = 
 [[ 7 10]
 [15 22]] 



In [337]:
d=np.array([[[1,2],[3,4]]])
print("d= \n",d,"\n")
print(d.shape)

print("np.dot(d,d) = \n",np.dot(d,d),"\n")

print("a.dot(d) = \n",a.dot(d),"\n")  # you can call `dot` directly on the `ndarray`

print("np.matmul(d,d) = \n",np.matmul(d,d),"\n")

d= 
 [[[1 2]
  [3 4]]] 

(1, 2, 2)
np.dot(d,d) = 
 [[[[ 7 10]]

  [[15 22]]]] 

a.dot(d) = 
 [[[ 7 10]]

 [[15 22]]] 

np.matmul(d,d) = 
 [[[ 7 10]
  [15 22]]] 



In [339]:
a.dot(d)

array([[[ 7, 10]],

       [[15, 22]]])

In [340]:
np.dot(a,d)

array([[[ 7, 10]],

       [[15, 22]]])

In [133]:
np.dot(d,d).shape

(1, 2, 1, 2)

In [137]:
np.matmul(d,d).shape

(1, 2, 2)

In [138]:
d@d

array([[[ 7, 10],
        [15, 22]]])

In [139]:
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)
c = (a@b)
d = np.dot(a,b)


In [140]:
print(c,c.shape)


[[[0.88884799 0.52244199 1.2962849 ]
  [0.52623401 0.29607045 0.56971947]
  [0.82892358 0.45954226 0.96559505]]

 [[0.54585037 0.29846235 0.81609956]
  [0.31242066 0.41023455 0.80023018]
  [0.49673515 0.59446143 0.71062509]]] (2, 3, 3)


In [141]:
print(d,d.shape)

[[[[0.88884799 0.52244199 1.2962849 ]
   [0.6519152  0.45659635 1.24112233]]

  [[0.52623401 0.29607045 0.56971947]
   [0.24160949 0.40215894 0.36044575]]

  [[0.82892358 0.45954226 0.96559505]
   [0.39964043 0.55250052 0.71281442]]]


 [[[0.47021225 0.32724321 0.80193338]
   [0.54585037 0.29846235 0.81609956]]

  [[0.81309289 0.41589764 0.97338876]
   [0.31242066 0.41023455 0.80023018]]

  [[0.78379853 0.46978161 0.95633858]
   [0.49673515 0.59446143 0.71062509]]]] (2, 3, 2, 3)


In [146]:
# *
a = np.array([[1,2,3],[5,6,7]])
print(a.shape)
print(a*a)


(2, 3)
[[ 1  4  9]
 [25 36 49]]


In [147]:
#np.multiply
print(np.multiply(a,a))
print(np.multiply(a,a).shape)

[[ 1  4  9]
 [25 36 49]]
(2, 3)


In [148]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [149]:
np.dot(a, b) 

32

In [152]:
a = np.array([[1,2,3],[5,6,7]])
np.dot(a,a.T)

array([[ 14,  38],
       [ 38, 110]])

In [342]:
a=np.array([ [[1,2],[1,2]], [[1,3],[1,3]], [[1,4],[1,4]]
    
])
a

array([[[1, 2],
        [1, 2]],

       [[1, 3],
        [1, 3]],

       [[1, 4],
        [1, 4]]])

In [343]:
print(a@a)

[[[ 3  6]
  [ 3  6]]

 [[ 4 12]
  [ 4 12]]

 [[ 5 20]
  [ 5 20]]]


In [344]:
print(np.dot(a,a))

[[[[ 3  6]
   [ 3  9]
   [ 3 12]]

  [[ 3  6]
   [ 3  9]
   [ 3 12]]]


 [[[ 4  8]
   [ 4 12]
   [ 4 16]]

  [[ 4  8]
   [ 4 12]
   [ 4 16]]]


 [[[ 5 10]
   [ 5 15]
   [ 5 20]]

  [[ 5 10]
   [ 5 15]
   [ 5 20]]]]


In [345]:
a*a

array([[[ 1,  4],
        [ 1,  4]],

       [[ 1,  9],
        [ 1,  9]],

       [[ 1, 16],
        [ 1, 16]]])

In [346]:
np.sum(a*a, axis=1)

array([[ 2,  8],
       [ 2, 18],
       [ 2, 32]])

In [349]:
sum(a*a)

array([[ 3, 29],
       [ 3, 29]])

While these functions return the same results for two dimensional data, we should be careful about which we choose when working with other data shapes.

### Transpose
Getting the transpose of a matrix is really easy in NumPy. Simply access its ```T``` attribute. There is also a ```transpose()``` function which returns the same thing, but we’ll rarely see that used anywhere because typing ```T``` is much easier.
For example:

In [351]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("m =\n",m,"\n")

print("m.T = \n ",m.T)
print("\n m.transpose = \n",m.transpose())

m =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

m.T = 
  [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

 m.transpose = 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


NumPy does this without actually moving any data in memory - it simply changes the way it indexes the original matrix - so it’s quite efficient.

However, that also means we need to be careful with how we modify objects, because **they are sharing the same data**. For example, with the same matrix ```m``` from above, let's make a new variable ```m_t``` that stores ```m```'s transpose. Then look what happens if we modify a value in ```m_t```:

In [352]:
m_t = m.T
m_t[3][1] = 200
print("m_t = \n",m_t, "\n")

print("m = \n",m)

m_t = 
 [[  1   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4 200  12]] 

m = 
 [[  1   2   3   4]
 [  5   6   7 200]
 [  9  10  11  12]]


Notice how it modified both the transpose and the original matrix, too! That's because they are sharing the same copy of data. So remember to consider the transpose just as a different view of we matrix, rather than a different matrix entirely.

### A real use case
I don't want to get into too many details about neural networks because we haven't covered them yet, but there is one place we will almost certainly end up using a transpose, or at least thinking about it.

Let's say we have the following two matrices, called ```inputs``` and ```weights```,

In [170]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
print("inputs = \n",inputs)

print("inputs.shape: ",inputs.shape, "\n")

weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

print("weights = \n",weights)

print("weights.shape: ",weights.shape, "\n")

inputs = 
 [[-0.27  0.45  0.64  0.31]]
inputs.shape:  (1, 4) 

weights = 
 [[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]
weights.shape:  (3, 4) 



If we try it like they are now, we get an error:

In [171]:
print(np.matmul(inputs, weights))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

This error of incompatible shapes is because the number of columns in the left matrix, ```4```, is not equal the number of rows in the right matrix, ```3```. <br>
So that doesn't work, but notice if we take the transpose of the ```weights``` matrix, it will:

In [172]:
print("np.matmul(inputs, weights.T) = \n",np.matmul(inputs, weights.T))

np.matmul(inputs, weights.T) = 
 [[-0.01299  0.00664  0.13494]]


In [173]:
oldT = np.matmul(inputs, weights.T)
oldT.shape

(1, 3)

It also works if we take the transpose of inputs instead and swap their order

In [174]:
print(np.matmul(weights, inputs.T))

[[-0.01299]
 [ 0.00664]
 [ 0.13494]]


In [175]:
newT = np.matmul(weights, inputs.T)
newT.T.shape

(1, 3)

The two answers are transposes of each other, so which multiplication we use really just depends on the shape we want for the output.

## Sorting, Subsetting, Slicing, Splitting and Indexing

Data handling is one of the most important skills to have as a data scientist. NumPy provides a suite of data handling functions. We are going to look at a few of them here.

### Sorting

To sort any NumPy array we use the ```np.sort``` function:

In [176]:
a = np.array([[7,32,1],[55,0,-6],[3,99,20]])
print(a, "\n")
print(np.sort(a),"\n")
print(np.sort(a, axis =0))

[[ 7 32  1]
 [55  0 -6]
 [ 3 99 20]] 

[[ 1  7 32]
 [-6  0 55]
 [ 3 20 99]] 

[[ 3  0 -6]
 [ 7 32  1]
 [55 99 20]]


By default, the elements are sorted in ascending order with respect to the last dimension, which in this case is the column dimension. We can also sort the elements with respect to the rows.

In [177]:
print(a, "\n")
print(np.sort(a, axis = 0))

[[ 7 32  1]
 [55  0 -6]
 [ 3 99 20]] 

[[ 3  0 -6]
 [ 7 32  1]
 [55 99 20]]


We can also sort all the elements in a 1 dimensional array by setting ```axis``` to ```None```

In [178]:
print(np.sort(a, axis=None))

[-6  0  1  3  7 20 32 55 99]


### Subsetting

Just like sets in mathematics, ```ndarray```'s also have subsets. We will look at some possible subsets of a 2D array (matrix)

In [353]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1][3])

# print(a[1,3])

# print(a[0])
# print(a[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8


In [354]:
print(a[1,3])
print(a[2,1])

8
10


In [183]:
print(a[0])

[1 2 3 4]


In [184]:
print(a[:,2])

[ 3  7 11]


Here, ```a[1][3]``` and ```a[1,3]``` both give the same output: The 4th element of the 2nd row; ```a[0]``` gives the entire 1st row where as ```a[:,2]``` gives all the row elements associated with the 3rd column. <br>
It should be noted that all of these are considered as subsets of the array ```a```.

### Slicing

Similar to subsetting, slicing allows us to extract certain portions of an array. For example

In [355]:
a = np.arange(10) # a 1D array from 0 to 9
print(a)
s = slice(0,10,2)
# print(a[s])
print(s)

[0 1 2 3 4 5 6 7 8 9]
slice(0, 10, 2)


Here, the tuple (2,9,2) means that ```s``` should start with the value ```2```, end at value ```9``` and take steps of ```2``` to get to ```9```. Or we could simply write

In [198]:
a=np.array([67,68,69,89,642,65,9,10])
s=slice(0,650,2)
print(a[s])

[ 67  69 642   9]


In [204]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [207]:
s = a[2:9:2]
print(s)

[2 4 6 8]


In both of these examples, we have picked a certain slice of the original array ```a```.

We can also something like this

In [211]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [212]:
print(a[::-2])

[9 7 5 3 1]


In [214]:
print(a[:3:-2])

[9 7 5]


Here ```-1``` indicates the reverse order.

### Indexing

Although we have already seen indexing at work, there are a few things worth mentioning to develop a better intuition about how NumPy arrays, and to the extent, how tensors in TensorFlow can be handled.

In [217]:
a[a>5]

array([6, 7, 8, 9])

In [370]:
print(a[(a>5) & (a==5)])

[]


In the above example, known as boolean indexing, we put a condition on ```a```'s elements of being greater than 5. This kind of conditional filtering also proves helpful sometimes.

In [366]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


There is depth to the overall working of the NumPy stack in Python, but for the horizon of our course, this much would suffice. <br>
### Thank you .

In [95]:
a = np.array(range(0,81))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80]


In [99]:
a[25 between 35]
print(b)

[36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80]


In [100]:
c = a[a<35]
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [106]:
d = a[a>25]
d[d<35]

array([26, 27, 28, 29, 30, 31, 32, 33, 34])

In [108]:
c = a[(a>25) & (a<35)]
print(c)

[26 27 28 29 30 31 32 33 34]


In [223]:
g=np.array([[[1,2]],[[2,2]],[[1,2]],[[2,2]]])

In [224]:
g.shape

(4, 1, 2)

In [225]:
np.ones([2,2,1,2])

array([[[[1., 1.]],

        [[1., 1.]]],


       [[[1., 1.]],

        [[1., 1.]]]])